### ISSUE TITLE
Unexpected end-group tag.

### ISSUE THREAD

**Issue by Ghxst** [marin-m/pbtk#17]
Hey, could you tell me what causes the following error?

```
Traceback (most recent call last):
  File ".\gui.py", line 328, in launch_fuzzer
    self.get_params = self.transport.load_sample(sample, self.pb_request)
  File "C:\Users\Ghxst\Downloads\pbtk-master\pbtk-master\utils\transports.py", line 30, in load_sample
    pb_msg.ParseFromString(bytes.fromhex(sample))
  File "C:\Program Files\Python38\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Program Files\Python38\lib\site-packages\google\protobuf\internal\python_message.py", line 1148, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
```

It's possible I'm doing something wrong when fuzzing, I am taking the request from HexView in Fiddler and using that as the raw POST data.

**Comment by marin-m** [comment]
Hello,

It seems that the hexadecimal string that you entered in first place may not be correct Protobuf (it may be prefixed or suffixed by something else for example, or just another format).

You should first verify its validity through the command line using the `protoc` (Protobuf compiler, from Google) utility. Here is how you can do it on Linux:

```bash
echo YOUR_HEXADECIMAL_STRING | xxd -r -p | protoc --decode_raw
```

(`xxd -r -p` is a command that just decodes from hexadecimal through an utility that is available in most Linux distribution's repository, but you should also be able to use `python3 -c "import sys; sys.stdout.buffer.write(bytes.fromhex(sys.stdin.read().strip()))"` or whatever else.)

Regards,
