### ISSUE TITLE
Use pacaur instead of yaourt

### ISSUE THREAD

**Issue by addcninblue** [marin-m/pbtk#2]
Yaourt is dangerous, as it executes the PKGBUILD instead of letting the user view it before executing. Pacaur should be used instead.

References:
[Arch Wiki](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table)
[Reddit explanation](https://www.reddit.com/r/archlinux/comments/4azqyb/whats_so_bad_with_yaourt/)

**Comment by marin-m** [comment]
Hello,

Thanks, I acknowledge the yaourt behaviour you mention.

If your request is about editing the installation procedure present on the main project page, I would like to point out that:
* I don't think any concrete malicious behaviour is likely to have already relied on it, as Arch repos are a way less interesting attack target than a lot of external binary sources that are being relied on by popular AUR packages, and won't be as checked and visible as PKBGUILDs.
* Most of time, those being no more user checked than sources anyway.
* This is a very specialized security project that is not likely to be browsed by a lot of Archlinux users, and even less to influence their choice regarding the package manager they are using, when thinking about their whole interaction from an ergonomic point of view. I appreciate your initiative but it is likelier to come out as useful (risk surface and bulk potential userbase-wise) anywhere else.
* yaourt has three times the amount of [votes](https://aur.archlinux.org/packages/?SB=v&SO=d&SO+=+a) for Pacaur, meaning that installation will be likelier to be performed in a somewhat smoother way for people using copy-paste.

Thus, the benefit for the cost of including an explanation about the advantages of using Pacaur over yaourt near the introductory part of the README does not seem obvious. I'm still listening if however you have reasons not to think so and you can think of a concise and likely to be helpful way to insert it.

Regards

**Comment by marin-m** [comment]
Hello,

As `yay` superseded `yaourt` in popularity, I replaced it by the former in the `README.md` file. Hence, I'm closing this issue.

Regards,
