### ISSUE TITLE
google-chrome binary is missing

### ISSUE THREAD

**Issue by jjhesk** [marin-m/pbtk#20]
I have install all the tools 

Installing collected packages: PyQt5-sip, PyQt5-Qt, PyQtWebEngine-Qt, PyQt5, pyqtwebengine
Successfully installed PyQt5-5.15.3 PyQt5-Qt-5.15.2 PyQt5-sip-12.8.1 PyQtWebEngine-Qt-5.15.2 pyqtwebengine-5.15.3

but i still getting `ImportError: You are missing the binary "google-chrome" for this.`

**Comment by marin-m** [comment]
Hello,

This specific feature requires to install Chromium or Google Chrome system-wide.

Different paths or commands for attempting to find Chrome/Chromium are tried here: https://github.com/marin-m/pbtk/blob/5b78ab4/extractors/web_extract.py#L40

Also, are you trying to use a command line endpoint? The main way to run this application is to type the `./gui.py` command (or `pbtk` if you installed a distribution package).

**Comment by jjhesk** [comment]
tried both `./gui.py` and bin package. I also have Chrome/Chromium installed as the browser. Using macosx the 11.1 Beta (20C5048k) version

**Comment by marin-m** [comment]
Hello,

I have pushed a tentative fix in commit 777254e. Does it work better for you with this version?

Regards,

**Comment by jjhesk** [comment]
yes, its working. I will keep testing it .
