### ISSUE TITLE
install on Debian

### ISSUE THREAD

**Issue by illbebach** [marin-m/pbtk#6]
FYI, I had to run the following command to get the program to run.

`pip3 install PyQtWebEngine`

Might consider revising README.md

**Comment by blackorzar** [comment]
In ubuntu I had to run the 

`pip3 install PyQtWebEngine`

and also had to run this command:

`sudo apt-get install libqt5x11extras5`

Please include them in the README file if possible.

I was getting this error:
> This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

**Comment by marin-m** [comment]
Thank you, should be fixed with commit            737c5e5.
